all:
  children:
    control:
      hosts:
        ops-01:
          ansible_host: 192.168.137.101
          ansible_user: user

    proxmox:
      hosts:
        pxm01:
          ansible_host: 192.168.137.241
          ansible_user: root
        pxm02:
          ansible_host: 192.168.137.242
          ansible_user: root

    lxc:
      children:
        proxy:
          hosts:
            caddy:
              ansible_host: 192.168.137.200
              ansible_user: root
        security:
          hosts:
            vaultwarden:
              ansible_host: 192.168.137.201
              ansible_user: root
            authentik:
              ansible_host: 192.168.137.202
              ansible_user: root
        dashboard:
          hosts:
            homarr:
              ansible_host: 192.168.137.203
              ansible_user: root
            tailscale:
              ansible_host: 192.168.137.209
              ansible_user: root
        monitoring:
          hosts:
            grafana:
              ansible_host: 192.168.137.204
              ansible_user: root
            prometheus:
              ansible_host: 192.168.137.205
              ansible_user: root
            uptime-kuma:
              ansible_host: 192.168.137.206
              ansible_user: root
        tools:
          hosts:
            code-server:
              ansible_host: 192.168.137.207
              ansible_user: root
        honeypot:
          hosts:
            opencanary:
              ansible_host: 192.168.137.208
              ansible_user: root

    pi:
      hosts:
        rpi-01:
          ansible_host: 192.168.137.50
          ansible_user: admin
