all:
  children:
    control:
      hosts:
        ops-01:
          ansible_host: 192.168.137.101
          ansible_user: user

    proxmox:
      hosts:
        pxm01:
          ansible_host: 192.168.137.241
          ansible_user: root
        pxm02:
          ansible_host: 192.168.137.242
          ansible_user: root

    vms:
      hosts:
        nessus:
          ansible_host: 192.168.137.105
          ansible_user: user

    lxc:
      children:
        proxy:
          hosts:
            caddy:
              ansible_host: 192.168.137.200
              ansible_user: root
        security:
          hosts:
            vaultwarden:
              ansible_host: 192.168.137.201
              ansible_user: root
        smart_home:
          hosts:
            homeassistant:
              ansible_host: 192.168.137.202
              ansible_user: root
        dashboard:
          hosts:
            glance:
              ansible_host: 192.168.137.203
              ansible_user: root
        monitoring:
          hosts:
            grafana:
              ansible_host: 192.168.137.204
              ansible_user: root
            prometheus:
              ansible_host: 192.168.137.205
              ansible_user: root
            uptime-kuma:
              ansible_host: 192.168.137.206
              ansible_user: root
        tools:
          hosts:
            adguard-backup:
              ansible_host: 192.168.137.51
              ansible_user: root
        storage:
          hosts:
            nextcloud:
              ansible_host: 192.168.137.208
              ansible_user: root
        network:
          hosts:
            tailscale:
              ansible_host: 192.168.137.209
              ansible_user: root
        media:
          hosts:
            stremio:
              ansible_host: 192.168.137.210
              ansible_user: root

    pi:
      hosts:
        rpi-01:
          ansible_host: 192.168.137.50
          ansible_user: admin
