all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    proxmox:
      hosts:
        pxm01:
          ansible_host: 10.10.1.241
        pxm02:
          ansible_host: 10.10.1.242
        pxm03:
          ansible_host: 10.10.1.243

    lxc:
      hosts:
        caddy:
          ansible_host: 10.20.0.200
        vaultwarden:
          ansible_host: 10.20.0.201
        homeassistant:
          ansible_host: 10.20.0.202
        glance:
          ansible_host: 10.20.0.203
        grafana:
          ansible_host: 10.20.0.204
        prometheus:
          ansible_host: 10.20.0.205
        uptime-kuma:
          ansible_host: 10.20.0.206
        adguard-backup:
          ansible_host: 10.20.0.51
        nextcloud:
          ansible_host: 10.20.0.208

    raspberry:
      hosts:
        pi:
          ansible_host: 10.20.0.50
          ansible_user: admin

    control:
      hosts:
        ansible-01:
          ansible_host: 10.20.0.100
