---
- name: Deploy Prometheus
  hosts: prometheus
  become: true
  tasks:
    - name: Create prometheus directory
      file:
        path: /opt/prometheus
        state: directory

    - name: Deploy prometheus config
      copy:
        dest: /opt/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'pxm01'
              static_configs:
                - targets: ['10.10.1.241:9100']

            - job_name: 'pxm02'
              static_configs:
                - targets: ['10.10.1.242:9100']

            - job_name: 'pxm03'
              static_configs:
                - targets: ['10.10.1.243:9100']

            - job_name: 'pi'
              static_configs:
                - targets: ['10.20.0.50:9100']

            - job_name: 'ansible'
              static_configs:
                - targets: ['10.20.0.100:9100']

            - job_name: 'caddy'
              static_configs:
                - targets: ['10.20.0.200:9100']

            - job_name: 'vaultwarden'
              static_configs:
                - targets: ['10.20.0.201:9100']

            - job_name: 'homeassistant'
              static_configs:
                - targets: ['10.20.0.202:9100']

            - job_name: 'glance'
              static_configs:
                - targets: ['10.20.0.203:9100']

            - job_name: 'grafana'
              static_configs:
                - targets: ['10.20.0.204:9100']

            - job_name: 'uptime-kuma'
              static_configs:
                - targets: ['10.20.0.206:9100']

            - job_name: 'adguard-backup'
              static_configs:
                - targets: ['10.20.0.51:9100']

            - job_name: 'nextcloud'
              static_configs:
                - targets: ['10.20.0.208:9100']

    - name: Deploy docker-compose
      copy:
        dest: /opt/prometheus/docker-compose.yml
        content: |
          services:
            prometheus:
              image: prom/prometheus:latest
              container_name: prometheus
              restart: unless-stopped
              ports:
                - 9090:9090
              volumes:
                - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
                - /opt/prometheus/data:/prometheus

    - name: Start prometheus
      shell: docker compose up -d
      args:
        chdir: /opt/prometheus
