name: Deploy Homelab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy Caddy
        run: ansible-playbook playbooks/deploy_caddy.yml -i inventories/hosts.yml

      - name: Deploy Vaultwarden
        run: ansible-playbook playbooks/deploy_vaultwarden.yml -i inventories/hosts.yml

      - name: Deploy Grafana
        run: ansible-playbook playbooks/deploy_grafana.yml -i inventories/hosts.yml

      - name: Deploy Prometheus
        run: ansible-playbook playbooks/deploy_prometheus.yml -i inventories/hosts.yml

      - name: Deploy Uptime Kuma
        run: ansible-playbook playbooks/deploy_uptime_kuma.yml -i inventories/hosts.yml

      - name: Deploy Adguard Backup
        run: ansible-playbook playbooks/deploy_adguard_backup.yml -i inventories/hosts.yml

      - name: Deploy Nextcloud
        continue-on-error: true
        run: ansible-playbook playbooks/deploy_nextcloud.yml -i inventories/hosts.yml

      - name: Deploy Stremio
        run: ansible-playbook playbooks/deploy_stremio.yml -i inventories/hosts.yml

      - name: Deploy Home Assistant
        run: ansible-playbook playbooks/deploy_homeassistant.yml -i inventories/hosts.yml

      - name: Deploy Glance
        run: ansible-playbook playbooks/deploy_glance.yml -i inventories/hosts.yml
