name: Deploy Homelab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible playbook
        run: |
          cd $GITHUB_WORKSPACE
          ansible-playbook playbooks/apps.yml -i inventories/hosts.yml --vault-password-file ~/.vault_pass
